image:
  name: hashicorp/terraform:0.11.11
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

before_script:
  - cd ./01-Infrastructure-Provisioning
  - echo $AWS_ACCESS_KEY
  - echo $AWS_SECRET_KEY
  - terraform --version
  - rm -rf .terraform
  - terraform init

stages:
  - validate
  - plan
  - apply

validate:
  stage: validate
  script:
    - terraform validate

plan:
  stage: plan
  script:
    - terraform plan -out "planfile" -var "access=$AWS_ACCESS_KEY" -var "secret=$AWS_SECRET_KEY"
    - ls -l
  dependencies:
    - validate
  artifacts:
    paths:
      - ./01-Infrastructure-Provisioning/planfile

apply:
  stage: apply
  script:
    - terraform apply -input=false "planfile"
  dependencies:
    - plan
  when: manual