stages:
  - build
  - deploy

variables:
  CONTAINER_IMAGE: igorvoitov/swagger_server
  CONTAINER_IMAGE_LATEST: ${CONTAINER_IMAGE}:${CI_PIPELINE_ID}
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375

build-image:
  stage: build
  image: docker:stable
  services:
  - docker:dind
  script:
    - cd ./02-Coding-skills-swagger
    - echo "Building Dockerfile-based application..."
    - docker build -t ${CONTAINER_IMAGE_LATEST} .
    - echo "username is $CI_REGISTRY_USER and password is $CI_REGISTRY_PASSWORD"
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - echo "Pushing to the Container Registry..."
    - docker push ${CONTAINER_IMAGE_LATEST}

deploy-helm:
  stage: deploy
  image: linkyard/docker-helm
  script:
    - echo "empty job"
#    - helm init --upgrade
#    - helm repo add stable https://kubernetes-charts.storage.googleapis.com
#    - helm upgrade --install  php-app --namespace default --wait --set image.tag=${CI_PIPELINE_ID} --set replicaCount=2 helm-data/