apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: aws-checker
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: aws-checker
    spec:
      containers:
      - name: aws-checker
        image: igorvoitov/swagger_server:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 250m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 256Mi
          env:          
          - name: "AWS_ACCOUNT_ID"
            valueFrom:
              secretKeyRef:
                key:  AWS_ACCOUNT_ID
                name: {{ .Release.Name }}-auth
          - name: "AWS_ACCESS_KEY"
            valueFrom:
              secretKeyRef:
                key:  AWS_ACCESS_KEY
                name: {{ .Release.Name }}-auth
          - name: "AWS_SECRET_KEY"
            valueFrom:
              secretKeyRef:
                key:  AWS_SECRET_KEY
                name: {{ .Release.Name }}-auth

---
apiVersion: v1
kind: Service
metadata:
  name: load-balancer
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
  selector:
    app: aws-checker
