apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  AWS_ACCOUNT_ID: {{ .Values.AWS_ACCOUNT_ID }}
  AWS_ACCESS_KEY: {{ .Values.AWS_ACCESS_KEY }}
  AWS_SECRET_KEY: {{ .Values.AWS_SECRET_KEY }}