# Default values for aws-checker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

AWS_ACCOUNT_ID: QVdTX0FDQ09VTlRfSUQ=
AWS_ACCESS_KEY: QVdTX0FDQ0VTU19LRVk=
AWS_SECRET_KEY: QVdTX1NFQ1JFVF9LRVk=