# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class AwsInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, region: str=None, state: str=None):  # noqa: E501
        """AwsInfo - a model defined in Swagger

        :param region: The region of this AwsInfo.  # noqa: E501
        :type region: str
        :param state: The state of this AwsInfo.  # noqa: E501
        :type state: str
        """
        self.swagger_types = {
            'region': str,
            'state': str
        }

        self.attribute_map = {
            'region': 'region',
            'state': 'state'
        }

        self._region = region
        self._state = state

    @classmethod
    def from_dict(cls, dikt) -> 'AwsInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AwsInfo of this AwsInfo.  # noqa: E501
        :rtype: AwsInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def region(self) -> str:
        """Gets the region of this AwsInfo.


        :return: The region of this AwsInfo.
        :rtype: str
        """
        return self._region

    @region.setter
    def region(self, region: str):
        """Sets the region of this AwsInfo.


        :param region: The region of this AwsInfo.
        :type region: str
        """

        self._region = region

    @property
    def state(self) -> str:
        """Gets the state of this AwsInfo.


        :return: The state of this AwsInfo.
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state: str):
        """Sets the state of this AwsInfo.


        :param state: The state of this AwsInfo.
        :type state: str
        """

        self._state = state
